# ???????? ?? ? ?????????????? ? ????????????
spring.datasource.url=jdbc:h2:file:./transaction;ACCESS_MODE_DATA=r
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=
spring.datasource.password=

# Liquibase ??? ?? ??????
spring.liquibase.enabled=true
spring.liquibase.url=jdbc:postgresql://localhost:5432/recommendation_rules
spring.liquibase.user=postgres
spring.liquibase.password=!Katya1706

# ?? ???????????? ??????
rule.datasource.url=jdbc:postgresql://localhost:5432/recommendation_rules
rule.datasource.username=postgres
rule.datasource.password=!Katya1706
rule.datasource.driver-class-name=org.postgresql.Driver

telegram.bot.name=starbank_recommendation_bot
telegram.bot.token=8996547911:AAEz2AGqs1lEaupoUH0yKH_DExKB7_ttSKk

server.port=8080