# ???????? ?? ? ?????????????? ? ????????????
spring.datasource.url=jdbc:h2:file:./transaction;ACCESS_MODE_DATA=r
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=
spring.datasource.password=
spring.liquibase.enabled=false


# ?? ???????????? ??????
rule.datasource.url=jdbc:postgresql://localhost:5432/recommendation_rules
rule.datasource.username=postgres
rule.datasource.password=!Katya1706
rule.datasource.driver-class-name=org.postgresql.Driver


server.port=8080